name: main
run-name: ${{ github.actor }} is pushing new code
on: [push]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      with:
        node-version: '18'
      - run: npm install
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint
